// Copyright 2018 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_temperature_measurement         15
#define gattdb_manufacturer_name_string         19
#define gattdb_model_number_string             21
#define gattdb_serial_number_string            23
#define gattdb_hardware_revision_string         25
#define gattdb_firmware_revision_string         27
#define gattdb_software_revision_string         29
#define gattdb_system_id                       31
#define gattdb_ieee_11073_20601_regulatory_certification_data_list         33
#define gattdb_pnp_id                          35
#define gattdb_ota_control                     38
#define gattdb_tx_power_level                  42

#endif
